language: perl
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libossp-uuid-dev libossp-uuid-perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
notifications:
    email:
        on_success: never
        on_failure: always
