Name:           perl-Iodef-Pb-Simple
Version:        0.21
Release:        1%{?dist}
Summary:        Perl extension providing high level API access to Iodef::Pb. It takes simple key-pair hashes and maps them to the appropriate IODEF classes using a Module::Pluggable framework of plugins
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Iodef-Pb-Simple/
Source0:        http://www.cpan.org/authors/id/S/SA/SAXJAZMAN/iodef/Iodef-Pb-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.8
BuildRequires:  perl(Class::Accessor) >= 0.34
BuildRequires:  perl(Compress::Snappy) >= 0.18
BuildRequires:  perl(DateTime) >= 0.61
BuildRequires:  perl(DateTime::Format::DateParse) >= 0.05
BuildRequires:  perl(Digest::SHA) >= 5.40
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Google::ProtocolBuffers) >= 0.08
BuildRequires:  perl(HTML::Table) >= 2.08
BuildRequires:  perl(JSON::XS) >= 2.29
BuildRequires:  perl(Module::Install) >= 1.00
BuildRequires:  perl(OSSP::uuid) >= 1.6.2
BuildRequires:  perl(Parse::Range) >= 0.96
BuildRequires:  perl(Regexp::Common::net) >= 2010010201
BuildRequires:  perl(Regexp::Common::net::CIDR) >= 0.02
BuildRequires:  perl(Snort::Rule) >= 1.07
BuildRequires:  perl(Text::Table) >= 1.126
Requires:       perl(Class::Accessor) >= 0.34
Requires:       perl(Compress::Snappy) >= 0.18
Requires:       perl(DateTime) >= 0.61
Requires:       perl(DateTime::Format::DateParse) >= 0.05
Requires:       perl(Digest::SHA) >= 5.40
Requires:       perl(Google::ProtocolBuffers) >= 0.08
Requires:       perl(HTML::Table) >= 2.08
Requires:       perl(JSON::XS) >= 2.29
Requires:       perl(Module::Install) >= 1.00
Requires:       perl(OSSP::uuid) >= 1.6.2
Requires:       perl(Parse::Range) >= 0.96
Requires:       perl(Regexp::Common::net) >= 2010010201
Requires:       perl(Regexp::Common::net::CIDR) >= 0.02
Requires:       perl(Snort::Rule) >= 1.07
Requires:       perl(Text::Table) >= 1.126
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This library provides high level access to the Iodef::Pb API. It allows for
the rapid generation of simple IODEF messages.

%prep
%setup -q -n Iodef-Pb-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes Makefile README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Dec 05 2013 Aaron K Reffett <akreffett@cert.org> 0.21-1
- Updated to upstream 0.21

* Wed May 29 2013 Aaron K Reffett <akreffett@cert.org> 0.18-3
- Added 'hash' to output if it exists
- Added PTR records to rdata output

* Fri May 03 2013 Aaron K Reffett <akreffett@cert.org> 0.18-1
- Added 'source' to hash

* Thu Feb 21 2013 Aaron K Reffett <akreffett@cert.org> 0.17-2
- Specfile autogenerated by cpanspec 1.78.
